"""removed_file_path

Revision ID: 0431574d2850
Revises: a3f75971eb18
Create Date: 2026-09-09 18:41:16.662892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0431574d2850'
down_revision: Union[str, Sequence[str], None] = 'a3f75971eb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_bucket', sa.String(), nullable=True))
    op.drop_column('documents', 'file_path')
    op.add_column('uploads', sa.Column('file_bucket', sa.String(), nullable=False))
    op.drop_column('uploads', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('uploads', 'file_bucket')
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'file_bucket')
    # ### end Alembic commands ###
