"""

Revision ID: 9e703a35941b
Revises: 247b23f9a0fe
Create Date: 2026-09-11 15:29:51.109128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e703a35941b'
down_revision: Union[str, Sequence[str], None] = '247b23f9a0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents_embeddings', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents_embeddings', type_='foreignkey')
    # ### end Alembic commands ###
