"""uploads_url

Revision ID: a3f75971eb18
Revises: 9795a93f1941
Create Date: 2026-09-09 18:15:16.374162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f75971eb18'
down_revision: Union[str, Sequence[str], None] = '9795a93f1941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('uploads', sa.Column('file_key', sa.String(), nullable=False))
    op.add_column('uploads', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('uploads', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('uploads', 'file_url')
    op.drop_column('uploads', 'file_key')
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
