[project]
name = "infra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mmaiokha", email = "maksym.maiokha.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "minio>=7.2.20",
    "pydantic-settings>=2.15.0",
]



[tool.uv]
package = false

