[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "minio>=7.2.20",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.42",
    "shared",
    "pgvector>=0.5.0",
]

[tool.uv]
package = true

[tool.uv.sources]
shared = { path = "../shared", editable = true }

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
